### ISSUE TITLE
python编译版本如何改为3.7

### ISSUE THREAD

**Issue by Aniderr** [TaleLin/lin-cms-flask#101]
执行pipenv install --dev的时候报错如下
Virtualenv location: C:\Users\Administrator\.virtualenvs\lin-cms-flask-19JFeIB4
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.6 (C:\Users\A\.\l\S\python.exe).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.

**Comment by smoryan** [comment]
pipfile里面，找python_version = "3.6"
改成3.7就好了

**Comment by sunlin92** [comment]
https://doc.cms.talelin.com/0.2.x/server/flask/questions.html
