### ISSUE TITLE
python版本3.8时，报错AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by shijunhong** [TaleLin/lin-cms-flask#102]
python3.8的文档中说明，time.clock()自Python 3.3起不推荐使用此功能，该功能已被删除：使用time.perf_counter()或time.process_time()代替，确定明确的行为。是不是要跟进下啊

**Comment by qiufeihong2018** [comment]
+1

**Comment by Aniderr** [comment]
请问题主有解决吗？

**Comment by shijunhong** [comment]
> 请问题主有解决吗？

最快的办法就是把版本改成3.7的啊

**Comment by Aniderr** [comment]
> 
> 
> > 请问题主有解决吗？
> 
> 最快的办法就是把版本改成3.7的啊


最快的办法是升级SQLAlchemy 和 flask-SQLAlchemy
