### ISSUE TITLE
lin-cms中wtf中使用optional校验器检查json对象时总为空

### ISSUE THREAD

**Issue by a616781689** [TaleLin/lin-cms-flask#103]
**描述 bug**
在编写一个Form的时候加了Optional校验器，发现没有执行我的自定义校验器。
- 你是如何操作的？
于是DEBUG了一下 发现Optional这个类的实现中__call__方法下进行了表单校验，其中引用的数据是field.raw_data，其它校验器引用的是field.data，debug中发现raw_data永远为空。
- 发生了什么？
Optional校验器永远判空，停止后续校验。
- 你觉得应该出现什么？
对于非空的参数应该不要停止校验
**你使用哪个版本出现该问题？**
Lin-CMS==0.2.0b2

**Comment by sunlin92** [comment]
#125 你好，这是一个bug，请参考这里解决，我们将在后续版本修复它
