### ISSUE TITLE
为后端部分编写Dockerfile制作Docker镜像

### ISSUE THREAD

**Issue by 99Kies** [TaleLin/lin-cms-flask#112]
CMS 是一个颇为复杂的应用，它需要的东西太多。我们无法涉及到方方面面，因此关于新特性，我们会以讨论的形式来确定这个特性是否去实现，以什么形式实现。
我们鼓励所有对这个特性感兴趣的人来参与讨论，当然如果你想参与特性的开发那就更好了。

如果你实现了一个 feature，并通过了单元测试，请用`git rebase`合并成一条标准的`feat: description`提交，然后向我们的
项目提 PR，我们会在第一时间审核，并感谢您的参与。
> 如果有考虑添加这个功能，我愿意尝试贡献code

**请问这个特性跟什么问题相关？ 有哪些应用场景？请详细描述。**
请清晰准确的描述问题的内容，以及真实的场景。
> 搭建环境更快速，应该主要是方便前端开发吧

**请描述一下你想怎么实现这个特性**
怎么样去实现这个特性？加入核心库？加入工程项目？还是其他方式。
当然你也可以描述它的具体实现.
> 添加Dockerfile

**讨论**
如果这个特性应用场景非常多，或者非常重要，我们会第一时间去处理。但更多的我们希望更多的人参与讨论，来斟酌它的可行性。

**Comment by sunlin92** [comment]
我们考虑过这个问题，目前Lin-CMS-Flask后端项目自身的依赖为Python运行环境和Mysql数据库，是比较简单的架构，第三方库的安装也比较方便，因此我们暂时不考虑使用Docker，毕竟对前端来说，Docker的使用也有一定的门槛。当然，如果您愿意，欢迎您将前后端项目打包的过程与大家分享~
