### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by guojiaxing1995** [TaleLin/lin-cms-flask#116]
请问下 之后项目是否会用到WebSocket相关的库
如果有
是使用Flask-Sockets 还是 Flask-SocketIO  或者其他什么
这2个库是不兼容的，目前项目需要，想选择和cms一致的，避免后续升级有问题。

**Comment by sunlin92** [comment]
你好，目前项目正在进行升级和重构，其中包含WebSocket部分，考虑到功能性和项目活跃度，我们将使用flask-socketio
