### ISSUE TITLE
主从数据库与分表访问的问题

### ISSUE THREAD

**Issue by fanyao1983** [TaleLin/lin-cms-flask#117]
大神好,在qq群里,没人解答,来这里提问
现在遇到2个问题.我们数据库变得非常庞大,之前用lin读写一体的,现在mysql经常锁死,和访问迟缓,因此公司数据库架构升级了,采用新的策略:分库分表,以及主从表.
问题1,现在数据库里有note_1,note_2,note_3...note99,100个表,是从原note表拆分的,在model里根据hash判断了要访问哪个表,但是定义class/db.model那里应该如何写
问题2.现在主数据库负责写,子数据库负责读,在lin的config->secure里,怎么指定数据库读写分离

**Comment by sunlin92** [comment]
1.lin-cms-flask-core中的db模块的代码不会影响分表，定义自己的数据模型类时实现分表逻辑即可；
2.读写分离不能通过简单的配置实现，详情参考这里：https://techspot.zzzeek.org/2012/01/11/django-style-database-routers-in-sqlalchemy/

**Comment by fanyao1983** [comment]
谢谢您


| |
樊耀
|
|
13951762324@163.com
|
签名由网易邮箱大师定制
在2020年7月20日 00:03，水月<notifications@github.com> 写道：

1.lin-cms-flask-core中的db模块的代码不会影响分表，定义自己的数据模型类时实现分表逻辑即可；
2.读写分离不能通过简单的配置实现，详情参考这里：https://techspot.zzzeek.org/2012/01/11/django-style-database-routers-in-sqlalchemy/
