### ISSUE TITLE
权限一对多的问题

### ISSUE THREAD

**Issue by cic1988** [TaleLin/lin-cms-flask#118]
请教一下目前多个权限可以assign给一个分组。如何把同一个权限assign给多个分组呢？比如editor可以同时edit和view。 viewer只能view。我看到代码里面目前auth的部分group_id只有一个id。谢谢。

**Comment by colorful3** [comment]
同一个权限分配给多个不同分组是支持的，可以使用前端编辑分组看下。超级管理员可以给不同的分组分配相同的权限。
