### ISSUE TITLE
请问flask版本什么时候会更新到和springboot相同的版本，有大致的时间节点吗

### ISSUE THREAD

**Issue by guojiaxing1995** [TaleLin/lin-cms-flask#119]
目前一套前端无法对应2套后端代码，2套后端要分别对应2套前端

**Comment by colorful3** [comment]
你好，感谢使用，等到发布正式版，可能要在10月了。
目前已重构大部分代码，还有些功能没有完成。

**Comment by frikyalong** [comment]
@colorful3 新版本大概什么时候会发布，

**Comment by youtai2020** [comment]
> @colorful3 新版本大概什么时候会发布，

同问

**Comment by sunlin92** [comment]
欢迎试用0.3.x分支，需要注意的是它目前处于测试阶段，如有问题请提issue，我们会尽快解决～
