### ISSUE TITLE
使用tinymac富文本编辑器顺序上传图片，第一张成功，之后就失败

### ISSUE THREAD

**Issue by skeletonli** [TaleLin/lin-cms-flask#121]
**使用tinymac富文本编辑器顺序上传图片，第一张成功，之后就失败**

使用tinymac插入第一张图片能正常显示，插入第二张时，前端报错：
Failed to load resource: net::ERR_CONNECTION_ABORTED

同时使用postman上传同一张图片就成功

**后端使用flask, 前端版本是 0.2.2**

tinymac用的是lin-cms的控件代码，无修改

**Comment by sunlin92** [comment]
你好，无法复现相同的问题，请提供更详细的运行环境帮助我们定位bug，谢谢
