### ISSUE TITLE
存在Optional()时会跳过其它验证

### ISSUE THREAD

**Issue by hastehu** [TaleLin/lin-cms-flask#125]
不使用lin.form验证正常，请问是封装哪里出问题了吗？
python版本3.6.8

**Comment by hastehu** [comment]
![图片](https://user-images.githubusercontent.com/30046961/99878273-2e859400-2c3f-11eb-8ba3-90f8f35bb0b7.png)
已解决

**Comment by sunlin92** [comment]
好的，感谢反馈~

**Comment by testnangua** [comment]
上面校验数组时**form.auths.data**会获取不到，接收需要这种格式：
formdata=ImmutableMultiDict([('group_id', 5), ('auths-0', '查询所有日志'), ('auths-1', '查询日志记录的用户')]) 
前端参数传递示例：
![image](https://user-images.githubusercontent.com/75116034/101236835-436a2900-370f-11eb-8178-4e6b61bb899c.png)
初学python能力有限，暂时这样可以解决，希望后面作者可以封装到lin.form里面吧

[python - 如何使用WTForms和flask验证数组？](https://www.coder.work/article/4960211)

**Comment by hastehu** [comment]
> 
> 
> 好的，感谢反馈~

**用ImmutableMultiDict 的话_**form.auths.data**_会获取不到，接收需要这种格式：
formdata=ImmutableMultiDict([('group_id', 5), ('auths-0', '查询所有日志'), ('auths-1', '查询日志记录的用户')])** 
前端参数传递示例：
![image](https://user-images.githubusercontent.com/75116034/101236835-436a2900-370f-11eb-8178-4e6b61bb899c.png)
初学python能力有限，暂时这样可以解决，希望后面可以封装到lin.form里面吧

[python - 如何使用WTForms和flask验证数组？](https://www.coder.work/article/4960211)
