### ISSUE TITLE
LocalUploader 图片上传返回的完整url路径bug

### ISSUE THREAD

**Issue by icolor** [TaleLin/lin-cms-flask#126]
返回到前端的路径为"http://127.0.0.1:5000/assets\\2020/11/26/97f35878-2f8e-11eb-86d5-9c5c8e6f3c44.jpg"
assets\\  这个正斜杠在js中调用出有转义问题

**Comment by sunlin92** [comment]
你好，无法复现此问题，请补充详细信息，谢谢~

![image](https://user-images.githubusercontent.com/40912737/100694910-06c6c680-33cb-11eb-8f96-ba8a2c52d592.png)


![image](https://user-images.githubusercontent.com/40912737/100694814-c7987580-33ca-11eb-9da9-80c504441974.png)

测试运行环境：
前端 lin-cms-vue 0.2.x 分支
后端 lin-cms-flask master 分支
数据库: sqlite3
浏览器: chrome 87.0.4280.67
操作系统：macos 10.15.7
其他配置保持默认
