### ISSUE TITLE
用户自定义定时任务

### ISSUE THREAD

**Issue by guojiaxing1995** [TaleLin/lin-cms-flask#14]
场景：对于用户的业务操作，可能用户想在一个特定时间去执行，但是那个时间点用户不能或没有时间去操作系统。  所以，希望有一个功能可以实现用户自定义的定时任务（用户定义时间、要执行的任务）。
 我目前用Flask-APScheduler 基本实现了这么一个功能。但还是有一些不完美的地方，例如用uwsgi部署时有问题。主要还是我自己能力有限，想看看如果要实现这样一个功能，更专业的开发者是怎么做的。

**Comment by ma3315865** [comment]
我觉得可以用celery来解决定时任务的问题

**Comment by RassinJ** [comment]
做个粒度比较大的时间轮，然后把用户自定义事件触发放到时间轮中去

**Comment by Jack-Kingdom** [comment]
uwsgi 下的应用需要把定时任务拆分出去，放在进程内没有跨进程的互斥锁可能会反复执行多次

**Comment by guojiaxing1995** [comment]
flask-apscheduler
