### ISSUE TITLE
建议在默认的包里添加`simplejson`包

### ISSUE THREAD

**Issue by hezygo** [TaleLin/lin-cms-flask#140]
### 如果使用默认的 _json_ 包进行 _jsonify_ 序列化 会产生 _RecursionError: maximum recursion depth exceeded while calling a Python object_ 异常,使用simplejson可以从根本上解决这个问题。

**Comment by sunlin92** [comment]
感谢反馈！我们将会尽快修复这个问题。

**Comment by sunlin92** [comment]
由于我们手头没有SQLServer环境，麻烦你尝试`feat/seralize/#140`分支是否解决了这个问题，确认后我们将合并到master
