### ISSUE TITLE
不太理解这种写法, 请教下

### ISSUE THREAD

**Issue by Holmes-pengge** [TaleLin/lin-cms-flask#143]
请教下，为什么在一个类中，会有这么多个构造函数？

![image](https://user-images.githubusercontent.com/35299284/106388182-54d26780-6418-11eb-951d-18d1ee5ac1ca.png)

**Comment by sunlin92** [comment]
![Screenshot_20210201-121101.jpg](https://user-images.githubusercontent.com/40912737/106414054-a1ed2280-6486-11eb-95ce-cf4bad9e3610.jpg)
可以查看这里的源码
