### ISSUE TITLE
关于按步骤配置项目，运行出错问题

### ISSUE THREAD

**Issue by J-zuo** [TaleLin/lin-cms-flask#146]
我按照入门开始：
1、克隆项目到本地
2、pip install -r requirements-dev.txt
3、因为我是第一次运行，所有执行了 flask db init

![F117469AAA2994672CF7630181A73E69](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-07-133606.jpg)

可我使用pip安装了flask啊 

![647FAF1799AA2353C42D607FA3C51B06](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-07-133608.jpg)

网上也找了资料，说是在～/.bash_profile文件中添加:

![44349F3F470D965BD74F81BF5DC22E47](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-07-133607.jpg)

还是不行，请问是哪里出了问题？

**Comment by sunlin92** [comment]
环境变量问题，或命令行中python与 pip对应版本不一致。

建议使用pyenv virtualenv解决。

或者直接指定使用当前Python3解释器
```
python3 -m pip install -r balabala.txt --user
python3 -m flask init db
python3 -m flask run
```

**Comment by J-zuo** [comment]
好的，使用了pycharm 的虚拟环境解决了问题
