### ISSUE TITLE
模仿book.py另写一个视图文件，访问不到

### ISSUE THREAD

**Issue by J-zuo** [TaleLin/lin-cms-flask#147]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
模仿book.py，另写一个 instrument.py,但是访问不到

这是定义的model:

<img src="http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-09-023836.png" alt="image-20210309103835544" style="zoom:50%;" />

这是视图中的代码：

<img src="http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-09-024030.png" alt="image-20210309104030616" style="zoom:50%;" />

从app.validator.schema中导入的 几个 xxxxSchema也模仿book中做了定义，最后访问

<img src="http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-09-024316.png" alt="image-20210309104316385" style="zoom:50%;" />

![image-20210309104721089](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-09-024726.png)

是我哪里没有配置好么？找不到问题，请教老师们

**Comment by sunlin92** [comment]
检查一下红图是否注册到了v1蓝图上。
[快速上手](https://doc.cms.talelin.com/start/flask/backend-demo.html#%E8%A7%86%E5%9B%BE%E6%8E%A7%E5%88%B6)
