### ISSUE TITLE
按照教程，已经卡住了，没找到原因

### ISSUE THREAD

**Issue by zj207036** [TaleLin/lin-cms-flask#148]
我用postman 这里就校验通不过，

![image-20210309165151927](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-09-085152.png)

为什么使用前端访问的时候可以

<img src="http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-09-085235.png" alt="image-20210309165235088" style="zoom:50%;" />

另外：/cms/user/auths这个方法好像没有，所以上图出错了。还是说我哪里没有注意到？
我的前端是0.2.x版本

**Comment by colorful3** [comment]
传参方式有误，要把 json 数据放到 body 里面。如下图所示：
<img width="935" alt="image" src="https://user-images.githubusercontent.com/29156058/110446618-5a4b5d80-80fa-11eb-9fa5-4c059995df56.png">
