### ISSUE TITLE
有点问题不解

### ISSUE THREAD

**Issue by zj207036** [TaleLin/lin-cms-flask#149]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。

![image-20210312203321836](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-12-123324.png)

![image-20210312203205188](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-12-123338.png)

我如何获取前端传参数呢，我看其他视图这里是用 request.context.json获取的
![image-20210312203538579](http://typora-ipic-image.oss-cn-hangzhou.aliyuncs.com/blog/2021-03-12-123542.png)

**Comment by sunlin92** [comment]
在api.validate装饰器中指定了json的校验模型，才能使用request.context.json获取前端的body json参数。
文档的[快速上手](https://doc.cms.talelin.com/start/flask/backend-demo.html#%E5%8F%82%E6%95%B0%E6%A0%A1%E9%AA%8C)部分用教程说明。

**Comment by zj207036** [comment]
好的，谢谢
