### ISSUE TITLE
lin-cms-vue如何配置多个数据库

### ISSUE THREAD

**Issue by tongtongking** [TaleLin/lin-cms-flask#151]
我当前的业务是基于lin-cms-vue进行开发的，但是现在需要进行多数据库连接，读取不同的数据库中的数据进行关联，我查看了flask官网，但是没有成功，希望能够给出一些提示和建议

**Comment by sunlin92** [comment]
flask是个微框架，数据库不属于它本体提供的功能。
[绑定多个数据库](http://www.pythondoc.com/flask-sqlalchemy/binds.html)
