### ISSUE TITLE
Model.get(one=False)获取数据时结果为空

### ISSUE THREAD

**Issue by DearXB** [TaleLin/lin-cms-flask#155]
我新建了一张表，想获取表中的所有数据，使用model.get(one=False)获取数据时得到的结果为空，然而我的数据库当中是有数据的。然而也并没有报错，于是查看源码并未找到解决方案，希望能得到帮助。

我的视图函数
![image](https://user-images.githubusercontent.com/44990847/118351504-fe380600-b58e-11eb-8f39-b1414184ed30.png)

控制台打印结果
[]
[2021-05-15 14:47:02,481] DEBUG in syslogger: [GET] -> [/v1/crawler] from:127.0.0.1 costs:2.000 ms data:{
        param: {},
        body: {}
}
127.0.0.1 - - [15/May/2021 14:47:02] "GET /v1/crawler HTTP/1.1" 200 -
数据库中数据
![image](https://user-images.githubusercontent.com/44990847/118351575-6b4b9b80-b58f-11eb-9fbc-e50094313582.png)

get源码
![image](https://user-images.githubusercontent.com/44990847/118351669-c4b3ca80-b58f-11eb-961c-33e2109e23c5.png)

**Comment by DearXB** [comment]
![image](https://user-images.githubusercontent.com/44990847/118352829-26773300-b596-11eb-9b5f-b901529a942b.png)
但是我在此视图函数则是正常的。返回结果如下：
![image](https://user-images.githubusercontent.com/44990847/118352860-57576800-b596-11eb-9a5e-7e91306a0e47.png)

**Comment by DearXB** [comment]
![image](https://user-images.githubusercontent.com/44990847/118354140-2ed26c80-b59c-11eb-91bb-70a6ae55a050.png)
当我这样写时可以正常返回数据，结果如下：
![image](https://user-images.githubusercontent.com/44990847/118354156-4c9fd180-b59c-11eb-88a5-8ae53bd7b16c.png)

**Comment by sunlin92** [comment]
delete_time字段非空视为软删除，在lin-cms中提供的查询方法会将这些数据过滤掉
