### ISSUE TITLE
0.2.x falsk 处理 数据新增后 直接返回或者间接查询返回都会 会报错 no attribut '_fields'

### ISSUE THREAD

**Issue by hezygo** [TaleLin/lin-cms-flask#156]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
![image](https://user-images.githubusercontent.com/58553737/118454256-be0d8a80-b72a-11eb-9e1e-b3dd25136024.png)

**Comment by sunlin92** [comment]
感谢反馈，这里的设计考虑不周，导致出现了此类问题。请尝试使用以下代码：
```python
    item = KGNode.create(**node_info, commit=True)
    item.init_on_load()
    return jsonify(item)
```

**Comment by hezygo** [comment]
> 感谢反馈，这里的设计考虑不周，导致出现了此类问题。请尝试使用以下代码：
> 
> ```python
>     item = KGNode.create(**node_info, commit=True)
>     item.init_on_load()
>     return jsonify(item)
> ```
使用后
上面那种 能够正确序列化，但是数据为null
下面这种 能够正确序列化且有数据。
```
    item_ = KGNode.create(**node_info, commit=True)
    item = KGNode.get(**node_info)
    item.init_on_load()
    return jsonify(item)
```
