### ISSUE TITLE
新增plugin后api访问报错

### ISSUE THREAD

**Issue by summerbuild** [TaleLin/lin-cms-flask#161]
**描述 bug**
1.使用flask plugin generate新增了一个test插件
2.使用flask plugin init初始化test插件
3.`app/config/__init__.py`自动导入了插件配置：
`PLUGIN_PATH = {
    'test': {'path': 'app.plugin.test', 'enable': True, 'version': '0.1.0'}
}`
4.访问http://localhost:5000/plugin/test，提示
`{"code": 20000, "message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "request": "GET  /plugin/test"}`

**你使用哪个版本出现该问题？**
使用master分支

**Comment by sunlin92** [comment]
感谢反馈，bug修复，请使用 [fix/#161](https://github.com/TaleLin/lin-cms-flask/tree/fix/%23161) 分支进行验证，谢谢~

**Comment by summerbuild** [comment]
验证，fix/#161 上已修复
