### ISSUE TITLE
头像更新返回URL无法访问

### ISSUE THREAD

**Issue by xiaoyunjie** [TaleLin/lin-cms-flask#163]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
更新头像，上传头像文件后，返回的user information中，avatar的地址是"http://127.0.0.1:5000/assets/2021/05/23/1235f7e4-bb1a-11eb-8eec-005056bdb92e.jpg"，客户端访问这个地址错误，头像加载失败。
如何调整SITE_DOMAIN，就是前面请求的地址和端口。
![image](https://user-images.githubusercontent.com/18340924/119248487-0feb6000-bbc4-11eb-92ea-6268f735e9e6.png)

**Comment by sunlin92** [comment]
![Screenshot_20210523-172827.jpg](https://user-images.githubusercontent.com/40912737/119255094-640a3a80-bbec-11eb-881d-6d54b4c8fafe.jpg) 根据实际的部署地址修改此项配置

**Comment by xiaoyunjie** [comment]
谢谢，已经找到相关配置，已解决
