### ISSUE TITLE
工厂函数读取配置文件应使用绝对路径

### ISSUE THREAD

**Issue by sunlin92** [TaleLin/lin-cms-flask#167]
![image](https://user-images.githubusercontent.com/40912737/124891613-bae89980-e00b-11eb-98ef-f04869c02962.png)
变更为
![image](https://user-images.githubusercontent.com/40912737/124891998-0dc25100-e00c-11eb-8b9f-c907fa0d82e0.png)
使create_app工厂函数在更多路径下的脚本适用

**Comment by colorful3** [comment]
LGTM
