### ISSUE TITLE
首次运行demo，加载js文件失败，求解

### ISSUE THREAD

**Issue by BestHotpot** [TaleLin/lin-cms-flask#169]
指向“https://cdn.jsdelivr.net/npm/swagger-ui-dist@3/swagger-ui-bundle.js”的 <script> 加载失败。

**Comment by BestHotpot** [comment]
访问：
http://127.0.0.1:5000/apidoc/swagger 


![28694D9D37CEDE3CED2D0FBB712A2E57](https://user-images.githubusercontent.com/4959422/125193604-d360ea00-e27f-11eb-981e-21f6e9ca5054.jpg)

**Comment by sunlin92** [comment]
看起来像网络问题，尝试在浏览器中直接访问js指向的地址，看看能不能打开
