### ISSUE TITLE
运行python starter.py命令时报错， no encoding declared

### ISSUE THREAD

**Issue by elevationly** [TaleLin/lin-cms-flask#17]
File "starter.py", line 13
SyntaxError: Non-ASCII character '\xe5' in file starter.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
python版本3.7.2 3.6.2均报错

**Comment by PedroGao** [comment]
这样的问题一般是你终端的编码问题，应该是windows的cmd的默认编码不是utf8，最好用bash

**Comment by elevationly** [comment]
> 这样的问题一般是你终端的编码问题，应该是windows的cmd的默认编码不是utf8，最好用bash

已解决，开始也以为是CMD的编码问题，后来发现是win10的原因，utf-8编码需要勾选才行

**Comment by legendjslc** [comment]
这个问题难道解决了吗？

**Comment by qiufeihong2018** [comment]
@PedroGao 需要用终端的话，难道要去改他的编码吗？这个也太变态了吧
