### ISSUE TITLE
pycharm debug启动与直接运行python starter.py    环境不一样的问题

### ISSUE THREAD

**Issue by madahademeng** [TaleLin/lin-cms-flask#170]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
![flask1](https://user-images.githubusercontent.com/33611273/129178461-2b2038ff-9a8d-417d-8436-93a83c0997c7.png)
![flask2](https://user-images.githubusercontent.com/33611273/129178465-98685d40-6007-42e3-bde8-f30cf5bd6c48.png)
如图，我想debug启动也加载 * Environment: development 环境，不知道应该改动下哪里

**Comment by sunlin92** [comment]
可能需要在IDE中进行配置，参考https://zhuanlan.zhihu.com/p/55485168配置启动脚本路径、参数和环境变量

**Comment by sunlin92** [comment]
可能需要在IDE中进行配置，参考[这个文章](https://zhuanlan.zhihu.com/p/55485168)配置启动脚本路径、参数和环境变量试试看
