### ISSUE TITLE
登录的时候，再做一下逻辑判断，需要在哪个位置写业务

### ISSUE THREAD

**Issue by sunchangpu** [TaleLin/lin-cms-flask#174]
我想在登录的时候，再做一下逻辑判断（比如用户会员是否已经到期，expire_time这个字段已经放进去了），应该在哪里写业务逻辑的 ？

这句话是做用户名，密码是否正确判断的的么？user = manager.user_model.verify(form.username.data, form.password.data)

![image](https://user-images.githubusercontent.com/25578290/138192360-8042dead-3636-40db-912e-1b65481639fd.png)

**Comment by sunlin92** [comment]
![图片](https://user-images.githubusercontent.com/40912737/138202665-f8044009-1e17-4a65-bffc-fd7215c3a43a.png)
