### ISSUE TITLE
初始化db报错

### ISSUE THREAD

**Issue by sunyinggang** [TaleLin/lin-cms-flask#178]
具体报错如下，我使用的是virtualenv
(venv) D:\MyCode\github\python\linCMS>flask db init
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'db'.

**Comment by sunlin92** [comment]
感谢反馈！已修复

**Comment by sunyinggang** [comment]
现在确实好使了，但是我看上边的merge内容，没发现是哪个改动解决了我这个问题，可以方便解答一下么，谢谢

**Comment by sunyinggang** [comment]
> 现在确实好使了，但是我看上边的merge内容，没发现是哪个改动解决了我这个问题，可以方便解答一下么，谢谢
