### ISSUE TITLE
你好,lin_permission表不更新权限

### ISSUE THREAD

**Issue by fanyao1983** [TaleLin/lin-cms-flask#180]
``
@book_api.route("/<int:id>", methods=["DELETE"])
@permission_meta(name="删除图书", module="图书")
@group_required
@api.validate(
    headers=AuthorizationSchema,
    resp=DocResponse(BookNotFound, Success(14)),
    tags=["图书"],
)
我把删除图书改为图书删除后, 
在分组里分配权限,查看依然是删除图书,打开数据库查看,lin_permission这个表的权限没有变化
我在v1里写了自己的代码,也都没有一点变化,请问是为什么,lin0.2版本是自动更新的,0.4版本要怎么做

**Comment by sunlin92** [comment]
感谢反馈。
0.4版本是指flask2分支吗，这个分支目前还在重构开发中，请使用master分支
