### ISSUE TITLE
现在确实好使了，但是我看上边的merge内容，没发现是哪个改动解决了我这个问题，可以方便解答一下么，谢谢

### ISSUE THREAD

**Issue by sunyinggang** [TaleLin/lin-cms-flask#181]
现在确实好使了，但是我看上边的merge内容，没发现是哪个改动解决了我这个问题，可以方便解答一下么，谢谢

_Originally posted by @sunyinggang in https://github.com/TaleLin/lin-cms-flask/issues/178#issuecomment-977889369_

**Comment by sunlin92** [comment]
- 开发环境依赖Pillow，没有同步到正式环境的依赖中
- 开发环境的核心库可以序列化bytes类型数据，正式环境中没有更新这个版本的核心库，所以需要将captcha工具类返回的bytes数据提前处理成string
