### ISSUE TITLE
db init

### ISSUE THREAD

**Issue by mark0-cn** [TaleLin/lin-cms-flask#184]
你好 请问一下这个报错怎么解决
![image](https://user-images.githubusercontent.com/59284400/149307870-d19ca7e5-08f7-4e42-a02e-c98f49d8c63d.png)

**Comment by sunlin92** [comment]
你好，请描述下代码的运行环境：
1. Python版本
2. 使用的操作系统
3. 数据库版本
4. 使用的项目分支/版本

**Comment by mark0-cn** [comment]
Python 3.7.0
win 10
5.5.53 MySQL
0.32

**Comment by mark0-cn** [comment]
好了好了 是数据库版本的事 感谢
