### ISSUE TITLE
windows下载，安装环境后，出现错误：Error: While importing 'starter', an ImportError was raised. 该怎么解决。谢谢

### ISSUE THREAD

**Issue by abbsmile** [TaleLin/lin-cms-flask#192]

**Comment by sunlin92** [comment]
- 使用python starter.py运行项目可以看到更详细的错误信息
- 使用[此分支](https://github.com/TaleLin/lin-cms-flask/tree/refactor/orm-compatibility)试一下能否解决这个问题

**Comment by sunlin92** [comment]
提问者没有回复，暂时关闭此issue
