### ISSUE TITLE
如果数据库选mysql新建时数据库里为空

### ISSUE THREAD

**Issue by Yuri2** [TaleLin/lin-cms-flask#202]
MySQL
根目录里的lincmsdev.db无法在mysql生成

**Comment by sunlin92** [comment]
你好，lincmsdev.db是开发环境下sqlite3数据库生成的数据文件，mysql应用使用自己配置的数据库，详情请参照文档[使用mysql](https://doc.cms.talelin.com/start/flask/#%E4%BD%BF%E7%94%A8-mysql)
