### ISSUE TITLE
消息的订阅与发布 ，flask 或java 有计划吗

### ISSUE THREAD

**Issue by sunchangpu** [TaleLin/lin-cms-flask#206]
0.0.。3q

**Comment by sunlin92** [comment]
消息订阅发布功能没有具体的实现，此功能过于依赖具体的业务场景

消息订阅发布可以基于ws实现：
- java的ws自带了权限验证机制，有需要可以看[文档 ](https://doc.cms.talelin.com/server/spring-boot/websocket.html)
- flask版本集成了flask-socketio库，有需要可以直接从`app.extension.notify.socketio`引入socketio对象自己实现相关业务
