### ISSUE TITLE
如何只获取已经被软删除的数据

### ISSUE THREAD

**Issue by ronething** [TaleLin/lin-cms-flask#21]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。

`lin/db.py`

```python
    def filter_by(self, soft=False, **kwargs):
        # soft 应用软删除
        if soft:
            kwargs['delete_time'] = None
        return super(Query, self).filter_by(**kwargs)
```

`filter_by(soft=True).all()` 或者 `filter_by(delete_time=None).all()` 可以获取没有被软删除的数据
`filter_by().all()` 可以获取所有数据

那么请问如何只获取已经被软删除的数据
使用 `filter(<Model>.delete_time != None).all()` 可以实现
⚠️使用 `filter_by()` 不知道怎么传参数 

可能是我对 `flask sqlalchemy` 不熟悉。
还望能够收到回复。谢谢。

**Comment by fujiale33** [comment]
您可以直接使用`filter(<Model>.delete_time != None).all()`这种方法实现。我们团队内部开发也是用这种方法的。

**Comment by ronething** [comment]
> 您可以直接使用`filter(<Model>.delete_time != None).all()`这种方法实现。我们团队内部开发也是用这种方法的。

👍 谢谢您的回复，那我就使用这种方法吧，我只是以为 `filter_by()` 也有办法解决。

**Comment by fujiale33** [comment]
谢谢您的支持！我们会继续坚持完善我们的开源项目。

**Comment by ronething** [comment]
> 谢谢您的支持！我们会继续坚持完善我们的开源项目。

不客气，希望你们可以坚持更新维护这个项目。

还有一点疑问。
```python
    def filter_by(self, soft=False, **kwargs):
        # soft 应用软删除
        if soft:
            kwargs['delete_time'] = None
        return super(Query, self).filter_by(**kwargs)
```

为何默认的 `soft=False` 而不是 `soft=True`
默认我们想要查询的数据不应该是没有被软删除的数据吗。
设置 `soft=True` 的话就不需要手动 `delete_time=None` 这样子。
问题好像有点蠢，希望可以得到您的解答。

**Comment by fujiale33** [comment]
哦，您看下自己Lin-CMS的版本号，应该不是最新的，我们在`Version 0.1.1a2`已经修改了这个问题，默认soft参数为True

**Comment by ronething** [comment]
> 哦，您看下自己Lin-CMS的版本号，应该不是最新的，我们在`Version 0.1.1a2`已经修改了这个问题，默认soft参数为True

emm, 我的版本号是 `lin-cms = "==0.1.1a3"` 跟代码仓库 `master` 分支 `Pipfile` 一样
刚刚在 https://pypi.org/project/Lin-CMS/0.1.1a3/#files 官方下载了 `0.1.1a3` 压缩包查看代码发觉是 False
![image](https://user-images.githubusercontent.com/28869910/53690014-8d391900-3d9d-11e9-81cf-62dfaf1efe87.png)
然后我又下载了 `0.1.1a2` 的 发觉是有设置 `True`
![image](https://user-images.githubusercontent.com/28869910/53690041-ffa9f900-3d9d-11e9-8cec-d0578e80b6b1.png)
讲道理 `0.1.1a3` 应该也有的吧。希望得到您的解答，谢谢。

**Comment by fujiale33** [comment]
哦   这应该是我们的问题，下个版本会修复，谢谢
