### ISSUE TITLE
返回 json 数据格式

### ISSUE THREAD

**Issue by ronething** [TaleLin/lin-cms-flask#22]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。

一点疑问：

发觉有些 api 接口返回格式没有统一的样子

例如 `log.py`

```python
    return jsonify({
        "total_nums": total_nums,
        "collection": logs
    })
```

请问为何不结合 APIException 返回一个统一的格式
例如增加 `data` 字段 (默认为空)

```
{
"error_code":xxx,
"code":xxx,
"msg":xxx,
"data":xxx
}
```

也有可能某些地方是我没考虑的。
还望收到回复。谢谢。

**Comment by fujiale33** [comment]
收到，你好。我们团队前端判断api返回的数据是根据http状态码来判断的，return jsonify()返回的http状态码为200，所以就没必要使用统一的数据格式返回。可以参考豆瓣开放api的一些获取数据的接口。
这个主要还是看团队内部的开发规范，如果自己团队需要规定api返回的数据格式，您也可以自定义一下。

**Comment by ronething** [comment]
> 收到，你好。我们团队前端判断api返回的数据是根据http状态码来判断的，return jsonify()返回的http状态码为200，所以就没必要使用统一的数据格式返回。可以参考豆瓣开放api的一些获取数据的接口。
> 这个主要还是看团队内部的开发规范，如果自己团队需要规定api返回的数据格式，您也可以自定义一下。

👍 谢谢您的回复。我就一个人。 只是提出一点疑问。

**Comment by fujiale33** [comment]
不客气，我们会继续坚持完善我们的开源项目的。谢谢支持！
