### ISSUE TITLE
如何修改初始化表名？

### ISSUE THREAD

**Issue by cl165** [TaleLin/lin-cms-flask#223]
想修改lin_user等表名，如何修改？

**Comment by sunlin92** [comment]
修改lin_user表名：
app/api/cms/model/user.py
```python
...
class User(LinUser):
    __tabelname__ = "你的表名"
    ....
```

**Comment by cl165** [comment]
> 修改lin_user表名： app/api/cms/model/user.py
> 
> ```python
> ...
> class User(LinUser):
>     __tabelname__ = "你的表名"
>     ....
> ```

试过了不行的

**Comment by sunlin92** [comment]
测试过确实不行。

表名在lincms核心库固定了字段，无法通过简单的继承修改。
项目根目录下有starter.py文件，其中
```
app = create_app(
...
    user_model=User,
...
)
```
手动挂载了User数据模型，可以仿照核心库的逻辑重写并挂载自己的数据模型，此时就可以使用`__tablename__`字段自定义表名了
