### ISSUE TITLE
InfoCrud、UserInterface

### ISSUE THREAD

**Issue by ronething** [TaleLin/lin-cms-flask#23]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。

`class InfoCrud`
```python
    @property
    def create_time(self):
        if self._create_time is None:
            return None
        return int(round(self._create_time.timestamp() * 1000))
```
是否可以考虑到用户要生成假数据给 `create_time` 一个 `setter` 方法
```python
    @create_time.setter
    def create_time(self, raw):
        self._create_time = raw
```

---

`class UserInterface`
是否可以不设置表名 即`__abstract__ = True`
然后在 `lin.core.py` 中`class User`再指定 `__tablename__='lin-user'`
这样如果我有自定义的`user_model` ,并且`user_model`的表名自定义例如 `my_user`
如果继承`UserInterface` 就不会自动生成 `lin-user` 表

可能我的想法中也有错误，希望可以收到您的回复，谢谢。

**Comment by ronething** [comment]
```python
    @property
    def create_time(self):
        if self._create_time is None:
            return None
        return int(round(self._create_time.timestamp() * 1000))
```
还有好奇这里返回毫秒级时间戳的用意，为何不直接返回秒级时间戳，
希望可以收到回复，谢谢。

**Comment by ronething** [comment]
> ```python
>     @property
>     def create_time(self):
>         if self._create_time is None:
>             return None
>         return int(round(self._create_time.timestamp() * 1000))
> ```
> 
> 还有好奇这里返回毫秒级时间戳的用意，为何不直接返回秒级时间戳，
> 希望可以收到回复，谢谢。

看起来是要用在前端方便转换的样子。

**Comment by PedroGao** [comment]
不好意思，回复慢了。

create_time为的是在数据生成的时候自动生成时间戳。如果需要做假数据的话，可以直接改变_create_time的值。

**Comment by PedroGao** [comment]
__tablename__='lin-user' 是可以在子类继承时进行覆盖的，你可以尝试在自己的model类中重新定义这个变量。

**Comment by ronething** [comment]
> **tablename**='lin-user' 是可以在子类继承时进行覆盖的，你可以尝试在自己的model类中重新定义这个变量。

谢谢你的回复，在我这里直接覆盖 `__ tablename __` 也是会生成 `lin-user` 表的，就是生成了两张 `user` 表。

**Comment by PedroGao** [comment]
看来`sqlalchemy`的table生成机制是根据`__tablename__`来的，我们后续会尝试用别的方案就行覆盖继承的，多谢反馈啊
