### ISSUE TITLE
关于编码的问题

### ISSUE THREAD

**Issue by legendjslc** [TaleLin/lin-cms-flask#24]
这个项目不错，用起来很好，但碰到了编码的问题。
在办公室的电脑上，一直可以正常用。但在家里的电脑上运行时，出现下面错误：
`
(venv) E:\Dev\python\sante-flask>Python starter.py
  File "starter.py", line 2
SyntaxError: Non-ASCII character '\xc2' in file starter.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`
我改动了所有.py文件，在第一行加上：
`
#coding=utf-8
`
以为会好了，但是，问题继续出现，但出现问题的路径变成了“C:\Python27\Lib\site-packages\lin”。还需要改下去吗？

我的疑惑是：
lin-CMS在文件头没有加编码注释，这个会不会导致出现编码问题？
都是pycharm，为啥有的不报错，有的就报错呢？是和IDE的设置有关吗？

期待您的答复，谢谢。

**Comment by PedroGao** [comment]
如果你是通过终端运行的，那么编码问题的不是代码，而是你的终端编码，请设置一下你的终端编码。

**Comment by legendjslc** [comment]
我是在win10下的，用的pycharm, 具体应该在哪里设呢？
虚拟机中ubuntu的pycharm居然也出同样的错误，奇怪了。

**Comment by PedroGao** [comment]
你直接用pycharm运行了？

**Comment by legendjslc** [comment]
是的，是把这个当个基本框架，开发一个小应用，结果根本就跑不起来了。

**Comment by PedroGao** [comment]
python3的默认编码就是utf8，不像python2，需要每次加上编码标示。我也在win10，mac，linux上都用过，均为出现编码问题，我觉得大概率是你的电脑的编码问题。建议你 `git reset --hard`回复成最初的状态再看一看。

**Comment by legendjslc** [comment]
卸载了电脑上装的好几个python版本后，只装了python 3.6.2(前面用的是python3.7.2)后，问题解决了。不知道是python3.7.2的问题，还是因为几个python版本冲突的问题，总之是不再报编码的错误了。
