### ISSUE TITLE
Cross-site request forgery Vulnerability in Latest Release

### ISSUE THREAD

**Issue by HatBoy** [TaleLin/lin-cms-flask#29]
Hi, I would like to report Cross-site request forgery vulnerability in latest release.

Description:
Cross-site request forgery(CSRF) vulnerability in app/api/cms/user.py and app/api/cms/admin.py.
When register, update user info, change password, delete user, disable user, active user, create group, etc do not validate to cause an CSRF vulnerability， Suggested to add Token.

author by jin.dong@dbappsecurity.com.cn

**Comment by 7insummer** [comment]
Thanks for these suggestions, as we have just started, including SQL injection and CSRF prevention has been put on the agenda but has not yet been achieved. We will improve these security issues in the near future. Thanks again.
