### ISSUE TITLE
Identity authentication vulnerability in Latest Release

### ISSUE THREAD

**Issue by HatBoy** [TaleLin/lin-cms-flask#30]
Hi, I would like to report Cross Site Scripting vulnerability in latest release.

Description:
Identity authentication vulnerability in the logout, When you log out, the authentication token is still valid.

Steps To Reproduce:
1.Login the background
2.Do something, like list users
3.Logout
4.Replay packet, can see the user list.
![4](https://user-images.githubusercontent.com/8274796/54364496-f9722180-46a7-11e9-842b-3f2406983f98.png)
author by jin.dong@dbappsecurity.com.cn

**Comment by 7insummer** [comment]
Thanks for these suggestions, as we have just started, including SQL injection and CSRF prevention has been put on the agenda but has not yet been achieved. We will improve these security issues in the near future. Thanks again.

**Comment by 7insummer** [comment]
This should be a bug. Thank you very much. Let's check it out。

**Comment by OS-WS** [comment]
Hi @7insummer @HatBoy ,
Was this issue fixed?
if so, in what commit and what tag/version?
thanks!

**Comment by sunlin92** [comment]
This shouldn't be a bug and there is no plan to fix it.

**Comment by epicosy** [comment]
Is this the fix? https://github.com/TaleLin/lin-cms-flask/commit/df25a77b853b062b5ba41b9701ce4975d176dcfa
