### ISSUE TITLE
v1/book/1接口测试失败，返回error code 10000

### ISSUE THREAD

**Issue by liujianfeng1020** [TaleLin/lin-cms-flask#49]
> {"error_code": 10000, "msg": "\u8ba4\u8bc1\u5931\u8d25\uff0c\u8bf7\u68c0\u67e5\u8bf7\u6c42\u5934\u6216\u8005\u91cd\u65b0\u767b\u9646", "request": "GET  /v1/book/1"}

当我按照
http://doc.cms.7yue.pro/lin/start/flask/backend-demo.html#%E8%A7%86%E5%9B%BE%E6%8E%A7%E5%88%B6 这个文档进行测试的时候，浏览器打开
http://127.0.0.1:5000/v1/book/1
并没有返回'hello, I am a book'，而是返回最上面的err。

严格按照你们的文档来的，为什么不行呢？？

**Comment by liujianfeng1020** [comment]
@jwt.unauthorized_loader
def unauthorized_loader_callback(e):
    return AuthFailed(msg='认证失败，请检查请求头或者重新登陆')

搜到这里，原来是jwt的报错。怎么文档中没有提到它呢？

**Comment by fujiale33** [comment]
你好，此接口是一个受保护的接口，请求需要再header头里面携带token，直接使用浏览器访问是肯定不能成功的。建议使用postman接口调试工具，按照文档所说的，在header中携带login所生成的access_token才能成功访问此接口。

参考文档：
[](http://doc.cms.7yue.pro/lin/server/flask/token.html)

**Comment by liujianfeng1020** [comment]
> 你好，此接口是一个受保护的接口，请求需要再header头里面携带token，直接使用浏览器访问是肯定不能成功的。建议使用postman接口调试工具，按照文档所说的，在header中携带login所生成的access_token才能成功访问此接口。
> 
> 参考文档：
> [权限章节](http://doc.cms.7yue.pro/lin/server/flask/token.html)

谢谢指点。这个是后面的章节了，在“新手入门”当中并没有写，所以我没有注意到。
你们现在最新的代码，都要token了，否则不能test了。希望能在新手入门处增加说明或链接。

谢谢：D

**Comment by fujiale33** [comment]
谢谢你的建议。
测试的话，建议还是跟着新手入门来手动改写，文档[新手入门](http://doc.cms.7yue.pro/lin/start/flask/backend-demo.html)的代码中并没有json web token的概念。所以你手动跟着新手入门这一块写代码，是不会报这个错误的。
我们也会完善文档这一块，尽量造成更少的误解。
