### ISSUE TITLE
添加用户交互体验不好~

### ISSUE THREAD

**Issue by zhenchengzj** [TaleLin/lin-cms-flask#5]
系统实际情况：
添加用户成功后，只是提示添加成功，依然停留在添加用户的界面，此时点击用户列表时，查询不到已添加的用户，我试了3次，都没有显示，最后只能F5刷新后才能显示出来，感觉交互体验不好。

我的理解：1、要么就是添加用户成功后，应返回到用户列表，这样操作者就能看到自己添加的信息是否真的成功的，但也有一个弊端，对于批量添加用户可能当前系统采用的更好，但是我觉得批量添加的情况比较少。
2、若保持当前系统状况，应该在用户点击用户列表时及时显示出最新的数据，这样也有弊端，需要频繁从数据库提取数据。但我认为一个好的产品，用户体验应该是第一位，尤其是开源的，越是傻瓜式的越好~
一点愚见~

**Comment by PedroGao** [comment]
多谢反馈，我们会逐步优化细节的。
