### ISSUE TITLE
没有lin-CMS 0.1.1版本，pip安装出错。

### ISSUE THREAD

**Issue by legendjslc** [TaleLin/lin-cms-flask#53]
下载后，安装需要的软件包：
`pip install -r requirements.txt`
出现以下错误信息。
` Could not find a version that satisfies the requirement Lin-CMS==0.1.1 (from -r requirements.txt (line 13)) (from versions: 0.1.1a1, 0.1.1a2, 0.1.1a3, 0.1.1a4, 0.1.1a5, 0.1.1a6, 0.1.1a7, 0.1.1a8, 0.1.1b1, 0.1.1b2)
No matching distribution found for Lin-CMS==0.1.1 (from -r requirements.txt (line 13))`
在https://pypi.org/网站上也只能找到Lin-CMS 0.1.1b2。
[https://pypi.org/project/Lin-CMS/](https://pypi.org/project/Lin-CMS/)

运行网站程序，出现以下错误：
`ImportError: cannot import name 'UserSuper' from 'lin.enums' (E:\Dev\python\hospital\sante-flask\venv370\lib\site-packages\lin\enums.py)`

这是怎么回事？

**Comment by fujiale33** [comment]
你好，看过你的问题。
第一，确认你的主工程版本号为master上的最新版本（即0.1.0-beta.1），其requirements.txt中的Lin-CMS版本号为 0.1.1b1 而不是0.1.1，这也是我们推荐的核心库稳定版本号。可以[点击下载release](https://github.com/TaleLin/lin-cms-flask/releases/tag/0.1.0-beta.1)
第二，运行starter.py报错的原因是由于你的Lin-CMS核心库版本号过低所导致，参考我们官方文档的[常见问题](http://doc.cms.7yue.pro/lin/server/flask/questions.html#%E6%A0%B8%E5%BF%83%E5%BA%93%E7%89%88%E6%9C%AC%E8%BF%87%E6%97%A7%E9%97%AE%E9%A2%98)，解决了第一个问题也就解决了第二个问题。
