### ISSUE TITLE
权限管理，每个权限分配装饰器都需要重复写一个group_required装饰器

### ISSUE THREAD

**Issue by JoeyGaojingxing** [TaleLin/lin-cms-flask#54]
**描述 bug**
![image](https://user-images.githubusercontent.com/15071824/57898348-3c5c9b00-788b-11e9-877c-5272b9d3493b.png)

group_required 装饰器和route_meta装饰器功能重复。这俩总要同时出现，可以合并

- 你觉得应该出现什么？
合并这两个装饰器

**Comment by fujiale33** [comment]
你好，group_required 装饰器和route_meta装饰器的功能不同的。
- route_meta装饰器主要是将视图函数的权限和模块信息存储到权限管理map中。
- group_required装饰器是校验管理员的token合法性以分组合法性。
如果将两个装饰器合并，程序的耦合度会被提高，这样的设计不是很好。

**Comment by JoeyGaojingxing** [comment]
那么想问一下，有什么情景需要单独使用某一个装饰器吗

**Comment by PedroGao** [comment]
route_meta可以搭配，login_required和admin_required分别使用。
当然，route_mate也可以单独使用，它表示该路由被加入到了权限体系中，**._requred类的装饰器，表示这个路由被某种程度上的守卫，它们不是一种东西。

**Comment by JoeyGaojingxing** [comment]
OK，我再去理解一下
