### ISSUE TITLE
关于cors

### ISSUE THREAD

**Issue by laozijiaojiangnan** [TaleLin/lin-cms-flask#67]
跨域是没有配置吗？

**Comment by fujiale33** [comment]
跨域可以自定义，你可以了解一下[flask_cors扩展](https://flask-cors.corydolphin.com/en/latest/api.html)

**Comment by JoeyGaojingxing** [comment]
跨域应该是默认配置好了，如果有跨域问题看看有没有40x，可能是服务器非正常响应导致的跨域，或者是部署也可能会影响
