### ISSUE TITLE
内置的CRUD方法可以多封装一些新特性

### ISSUE THREAD

**Issue by JoeyGaojingxing** [TaleLin/lin-cms-flask#73]
查询的时候，过滤字段以及多表关联查询都是非常常用的。但是内置封装的get函数不能满足这些需求，也不兼容原生的方法，所以涉及到这些方面的查询函数就要完全手写。但是这些内容往往才是最麻烦的。

同时，不一样的开发方法容易导致失误，比如，查询的时候没有过滤 `delete_time` 软删除字段，所以希望同一封装一些更高级的api，或者兼容原生api

**Comment by PedroGao** [comment]
内置的CRUD只是简单的CRUD，不能指望它去做复杂的查询，复杂的查询还是得靠QueryBuilder或者写`sql`
