### ISSUE TITLE
建议增加对swagger的支持

### ISSUE THREAD

**Issue by luanyuqiang** [TaleLin/lin-cms-flask#74]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。

**Comment by luanyuqiang** [comment]
目前项目没有对接接口文档，前后端对接很不方便

**Comment by PedroGao** [comment]
添加swagger都不难，自己就可以直接添加进去。可是有的有的人可能并不需要swagger，他们有其它的文档支持
