### ISSUE TITLE
【常见问题】项目部署到服务器后，启动5000端口外网依然无法访问

### ISSUE THREAD

**Issue by WangEn** [TaleLin/lin-cms-flask#75]
**【建议】文档-常见问题补充**
项目部署到服务器后，启动5000端口外网依然无法访问

**解决方案**
服务器环境示例： 腾讯云centos7
如果在开启服务器安全组和防火墙端口后，启动项目外网依然无法访问，请修改根目录starter.py末尾app.run()部分的代码，加入host参数并指定port端口

```
if __name__ == '__main__':
    app.run(host="127.0.0.1", port=5000, debug=True)
```
遇到问题时，搜索了一下，貌似flask都会有这个问题

**Comment by fujiale33** [comment]
部署到服务器上建议使用 uwsgi + flask + nginx，网上有很多教程。

**Comment by WangEn** [comment]
> 部署到服务器上建议使用 uwsgi + flask + nginx，网上有很多教程。

👌 好的，谢谢
