### ISSUE TITLE
运行python starter.py命令时报错：No module named 'flask'

### ISSUE THREAD

**Issue by heii** [TaleLin/lin-cms-flask#76]
> (starter) bash-3.2$ python starter.py
> Traceback (most recent call last):
>   File "starter.py", line 6, in <module>
>     from app.app import create_app
>   File "/Users/pc/Documents/starter/app/app.py", line 8, in <module>
>     from flask import Flask, request, g
> ModuleNotFoundError: No module named 'flask'

**Comment by fujiale33** [comment]
按照步骤，安装一下依赖

**Comment by heii** [comment]
MacMini:hk pc$ cd starter && pipenv install --dev
Installing dependencies from Pipfile.lock (e9cff1)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 41/41 — 00:00:11
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
MacMini:starter pc$ pipenv shell
Launching subshell in virtual environment…
bash-3.2$  . /Users/pc/.local/share/virtualenvs/starter-0fgtR3Zr/bin/activate
(starter) bash-3.2$ python starter.py
Traceback (most recent call last):
  File "starter.py", line 6, in <module>
    from app.app import create_app
  File "/Users/pc/Documents/hk/starter/app/app.py", line 8, in <module>
    from flask import Flask, request, g
ModuleNotFoundError: No module named 'flask'

按步骤又装了一次虚拟环境，还是报这个错误。

**Comment by fujiale33** [comment]
你好，执行下 pipenv graph 命令，看看依赖是否安装成功了呢。

**Comment by heii** [comment]
> cymysql==0.9.13
> Flask-Cors==2.1.0
>   - Flask [required: >=0.9, installed: 1.0.2]
>     - click [required: >=5.1, installed: 7.0]
>     - itsdangerous [required: >=0.24, installed: 1.1.0]
>     - Jinja2 [required: >=2.10, installed: 2.10.1]
>       - MarkupSafe [required: >=0.23, installed: 1.1.1]
>     - Werkzeug [required: >=0.14, installed: 0.14.1]
>   - Six [required: Any, installed: 1.12.0]
> Flask-WTF==0.14.2
>   - Flask [required: Any, installed: 1.0.2]
>     - click [required: >=5.1, installed: 7.0]
>     - itsdangerous [required: >=0.24, installed: 1.1.0]
>     - Jinja2 [required: >=2.10, installed: 2.10.1]
>       - MarkupSafe [required: >=0.23, installed: 1.1.1]
>     - Werkzeug [required: >=0.14, installed: 0.14.1]
>   - WTForms [required: Any, installed: 2.2.1]
> Lin-CMS==0.2.0b1
>   - Flask [required: ==1.0.2, installed: 1.0.2]
>     - click [required: >=5.1, installed: 7.0]
>     - itsdangerous [required: >=0.24, installed: 1.1.0]
>     - Jinja2 [required: >=2.10, installed: 2.10.1]
>       - MarkupSafe [required: >=0.23, installed: 1.1.1]
>     - Werkzeug [required: >=0.14, installed: 0.14.1]
>   - Flask-JWT-Extended [required: ==3.12.1, installed: 3.12.1]
>     - Flask [required: Any, installed: 1.0.2]
>       - click [required: >=5.1, installed: 7.0]
>       - itsdangerous [required: >=0.24, installed: 1.1.0]
>       - Jinja2 [required: >=2.10, installed: 2.10.1]
>         - MarkupSafe [required: >=0.23, installed: 1.1.1]
>       - Werkzeug [required: >=0.14, installed: 0.14.1]
>     - PyJWT [required: Any, installed: 1.7.1]
>     - Werkzeug [required: >=0.14, installed: 0.14.1]
>   - Flask-SQLAlchemy [required: ==2.3.2, installed: 2.3.2]
>     - Flask [required: >=0.10, installed: 1.0.2]
>       - click [required: >=5.1, installed: 7.0]
>       - itsdangerous [required: >=0.24, installed: 1.1.0]
>       - Jinja2 [required: >=2.10, installed: 2.10.1]
>         - MarkupSafe [required: >=0.23, installed: 1.1.1]
>       - Werkzeug [required: >=0.14, installed: 0.14.1]
>     - SQLAlchemy [required: >=0.8.0, installed: 1.2.11]
>   - SQLAlchemy [required: ==1.2.11, installed: 1.2.11]
>   - Werkzeug [required: ==0.14.1, installed: 0.14.1]
>   - WTForms [required: ==2.2.1, installed: 2.2.1]
> oss2==2.6.1
>   - aliyun-python-sdk-core-v3 [required: >=2.5.5, installed: 2.13.9]
>     - jmespath [required: >=0.9.3,<1.0.0, installed: 0.9.4]
>   - aliyun-python-sdk-kms [required: >=2.4.1, installed: 2.7.1]
>     - aliyun-python-sdk-core [required: >=2.11.5, installed: 2.13.9]
>       - jmespath [required: >=0.9.3,<1.0.0, installed: 0.9.4]
>   - crcmod [required: >=1.7, installed: 1.7]
>   - pycryptodome [required: >=3.4.7, installed: 3.9.0]
>   - requests [required: !=2.9.0, installed: 2.18.4]
>     - certifi [required: >=2017.4.17, installed: 2019.6.16]
>     - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
>     - idna [required: >=2.5,<2.7, installed: 2.6]
>     - urllib3 [required: >=1.21.1,<1.23, installed: 1.22]
> pipfile==0.0.2
>   - toml [required: Any, installed: 0.10.0]
> pytest==5.1.2
>   - atomicwrites [required: >=1.0, installed: 1.3.0]
>   - attrs [required: >=17.4.0, installed: 19.1.0]
>   - importlib-metadata [required: >=0.12, installed: 0.20]
>     - zipp [required: >=0.5, installed: 0.6.0]
>       - more-itertools [required: Any, installed: 7.2.0]
>   - more-itertools [required: >=4.0.0, installed: 7.2.0]
>   - packaging [required: Any, installed: 19.1]
>     - attrs [required: Any, installed: 19.1.0]
>     - pyparsing [required: >=2.0.2, installed: 2.4.2]
>     - six [required: Any, installed: 1.12.0]
>   - pluggy [required: >=0.12,<1.0, installed: 0.12.0]
>     - importlib-metadata [required: >=0.12, installed: 0.20]
>       - zipp [required: >=0.5, installed: 0.6.0]
>         - more-itertools [required: Any, installed: 7.2.0]
>   - py [required: >=1.5.0, installed: 1.8.0]
>   - wcwidth [required: Any, installed: 0.1.7]

装有很多东西，有点乱...

**Comment by fujiale33** [comment]
不应该啊。 flask 已经在虚拟环境中安装了。  要不你重新 clone 一下代码再按照步骤再走一遍。这个问题就是环境的问题。

**Comment by heii** [comment]
把mac重装了再重新配置环境就好了。。。
