### ISSUE TITLE
只有一个界面，没有管理后台么？

### ISSUE THREAD

**Issue by ppxstar** [TaleLin/lin-cms-flask#77]
同上

**Comment by fujiale33** [comment]
你好，该开源项目是前后端分离的CMS，你需要再 clone 一份前端的代码：链接为：[lin-cms-vue](https://github.com/TaleLin/lin-cms-vue) 
可以查看线上的[demo](http://face.cms.7yue.pro)

**Comment by ppxstar** [comment]
后来发现了，也跑起来了，但数据库里只生成了表结构，没有表数据怎么办？

**Comment by PedroGao** [comment]
数据是需要靠自己来填充的
