### ISSUE TITLE
config中log配置的等级无法生效

### ISSUE THREAD

**Issue by ye-xue** [TaleLin/lin-cms-flask#99]
在项目中config的log.py中LEVEL配置项没有生效,Linlog中是写死的logging.basicConfig(level=logging.DEBUG)

**Comment by fujiale33** [comment]
谢谢反馈！lin-cms-flask我们正在重构，兼容之前接口并方便用户配置，也希望持续关注。

**Comment by ye-xue** [comment]
请问你们重构大概什么时候完成呢?

**Comment by smoryan** [comment]
这个不是商业项目，没有工期保证的
